import React, { useEffect, useState, useMemo } from 'react';
import { AnalysisResult, ResearchPlan, ResearchContext, ProjectReport, ParticipantProfile } from '../types';
import { analyzeTranscripts, generateProjectReport } from '../services/geminiService';
import { getAllSessions, saveSession, SessionData, saveProjectReport, getProjectReport } from '../services/storage';
import { ResponsiveContainer, BarChart, Bar, XAxis, Tooltip, CartesianGrid, PieChart, Pie, Cell, Treemap, Sector } from 'recharts';
import { useLanguage } from '../contexts/LanguageContext';

interface GlobalDashboardProps {
  onBack: () => void;
}

// Professional Palette for Sentiment
const SENTIMENT_COLORS = {
    'positive': '#34C759', // Green
    'neutral': '#007AFF',  // Blue
    'negative': '#FF3B30', // Red
    'mixed': '#FF9500'     // Orange
};
// Fallback if specific keys aren't found
const BASE_COLORS = ['#007AFF', '#5856D6', '#34C759', '#FF9500', '#FF3B30', '#AF52DE'];

// Optimized Tech Palette for Heatmap (High Contrast, No Pale Colors)
const HEATMAP_COLORS = [
    '#007AFF', // System Blue
    '#5856D6', // Indigo
    '#00C7BE', // Teal
    '#32ADE6', // Cyan
    '#0063CC', // Dark Blue
    '#5E5CE6'  // Purple
];

// --- Advanced Markdown Parser Helper ---
const renderMarkdownContent = (content: string | undefined | null) => {
    if (!content) return null;

    // Pre-processing: Remove "robotic" titles generated by the prompt if present
    let processedContent = content
        .replace(/真实田野笔记/g, '真实的访谈片段')
        .replace(/^###\s*深度AI分析报告\s*/, '') // Remove meta-title
        .replace(/^\*\*深度AI分析报告\*\*\s*/, '')
        .trim();

    const lines = processedContent.split('\n');
    const renderedElements: React.ReactNode[] = [];
    
    let tableBuffer: string[] = [];
    let inTable = false;

    const flushTable = (keyPrefix: number) => {
        if (tableBuffer.length === 0) return null;
        
        // Basic table parsing
        const rows = tableBuffer.filter(l => l.trim().startsWith('|'));
        if (rows.length < 2) return null;

        const parseRow = (r: string) => r.split('|').filter(c => c.trim().length > 0 || c === '').map(c => c.trim());
        const header = parseRow(rows[0]);
        // rows[1] is separator |---|---|
        const body = rows.slice(2).map(parseRow);

        const tableEl = (
            <div key={`table-${keyPrefix}`} className="my-6 overflow-x-auto rounded-lg border border-gray-100">
                <table className="w-full text-left border-collapse text-sm">
                    <thead>
                        <tr className="bg-gray-50 border-b border-gray-200">
                            {header.map((h, i) => (
                                <th key={i} className="p-3 font-semibold text-gray-700 border-r border-gray-200 last:border-r-0 whitespace-nowrap">
                                    <span dangerouslySetInnerHTML={{ __html: h.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>').replace(/\*/g, '') }} />
                                </th>
                            ))}
                        </tr>
                    </thead>
                    <tbody>
                        {body.map((row, rI) => (
                            <tr key={rI} className="border-b border-gray-50 last:border-0 hover:bg-blue-50/30 transition-colors">
                                {row.map((cell, cI) => (
                                    <td key={cI} className="p-3 text-gray-600 border-r border-gray-100 last:border-r-0 align-top">
                                        <span dangerouslySetInnerHTML={{ __html: cell.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>').replace(/\*/g, '') }} />
                                    </td>
                                ))}
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        );
        tableBuffer = [];
        inTable = false;
        return tableEl;
    };

    lines.forEach((line, i) => {
        let trimmed = line.trim();
        
        // Table Detection
        if (trimmed.startsWith('|')) {
            inTable = true;
            tableBuffer.push(trimmed);
            return;
        } else if (inTable) {
            const table = flushTable(i);
            if (table) renderedElements.push(table);
        }

        if (trimmed === '') return;

        // Headers (H3/H4)
        if (trimmed.startsWith('###') || trimmed.startsWith('####')) {
            const level = trimmed.startsWith('####') ? 4 : 3;
            const cleanHeader = trimmed.replace(/^#+\s*/, '').replace(/\*\*/g, '').replace(/\*/g, '');
            
            renderedElements.push(
              <div key={i} className={`flex items-center gap-3 mt-8 mb-4 ${level === 3 ? 'pb-2 border-b border-gray-100' : ''}`}>
                 {level === 3 && <div className="w-1.5 h-6 bg-ios-blue rounded-full shadow-sm"></div>}
                 <h3 className={`${level === 3 ? 'text-lg text-gray-900' : 'text-base text-gray-800'} font-bold tracking-tight`}>
                    {cleanHeader}
                 </h3>
              </div>
            );
            return;
        }

        // Blockquote
        if (trimmed.startsWith('>')) {
            let cleanLine = trimmed.replace(/^>\s*/, '');
            cleanLine = cleanLine.replace(/\*\*(.*?)\*\*/g, '<strong class="text-blue-900">$1</strong>');
            renderedElements.push(
                <div key={i} className="relative pl-6 py-2 my-4 group">
                    <div className="absolute left-0 top-0 bottom-0 w-1 bg-blue-100 rounded-full group-hover:bg-blue-200 transition-colors"></div>
                    <p className="text-gray-600 italic leading-relaxed text-sm" dangerouslySetInnerHTML={{ __html: cleanLine }} />
                </div>
            );
            return;
        }

        // List Items (Numbered or Bullet)
        // Check for "1. ", "2. " OR "**1.** " patterns often output by AI
        const numberedListMatch = trimmed.match(/^(\d+\.|-|\*)\s+(.*)/) || trimmed.match(/^(\*\*\d+\.\*\*)\s+(.*)/);
        
        if (numberedListMatch) {
            let content = numberedListMatch[2] || trimmed; // Fallback if regex group 2 is undefined
            // Handle cases where bold key is part of the list item start like "**1. Key**: value"
            if (!numberedListMatch[2] && trimmed.includes('**')) {
                 content = trimmed; // Let internal logic handle it if regex failed to split cleanly
            }

            // Clean leading markers if they stuck around
            content = content.replace(/^(\d+\.|-|\*)\s+/, '').replace(/^\*\*\d+\.\*\*\s+/, '');

            // Formatting: **Text** -> Bold with color
            content = content.replace(/\*\*(.*?)\*\*/g, '<strong class="text-gray-900 font-bold">$1</strong>');
            
            const isNumbered = /^\d/.test(trimmed) || /^\*\*\d/.test(trimmed);

            renderedElements.push(
                <div key={i} className="flex gap-3 mb-3 ml-1">
                    {isNumbered ? (
                         <div className="flex-shrink-0 w-6 h-6 rounded-full bg-blue-50 text-ios-blue text-xs font-bold flex items-center justify-center mt-0.5 shadow-sm border border-blue-100">
                             {(trimmed.match(/\d+/) || ['•'])[0]}
                         </div>
                    ) : (
                        <div className="flex-shrink-0 w-6 h-6 flex items-center justify-center mt-0.5">
                            <div className="w-1.5 h-1.5 rounded-full bg-gray-300"></div>
                        </div>
                    )}
                    <p className="flex-1 text-gray-700 leading-relaxed text-sm pt-0.5 text-justify" dangerouslySetInnerHTML={{ __html: content }} />
                </div>
            );
            return;
        }

        // Regular Paragraph
        let htmlContent = trimmed;
        htmlContent = htmlContent.replace(/\*\*(.*?)\*\*/g, '<strong class="text-gray-900">$1</strong>');
        htmlContent = htmlContent.replace(/\*([^*]+)\*/g, '<span class="font-medium text-gray-800">$1</span>');
        
        renderedElements.push(
            <p key={i} className="mb-4 leading-relaxed text-gray-600 text-sm text-justify" dangerouslySetInnerHTML={{ __html: htmlContent }} />
        );
    });
    
    if (inTable) {
        const table = flushTable(lines.length);
        if (table) renderedElements.push(table);
    }

    return renderedElements;
};

// --- McKinsey Report Component (Visual Style Enforcement) ---
// Extracted to top level to avoid re-renders and closure issues
const McKinseyReportView = ({ report, sessions, onClose }: { report: ProjectReport, sessions: SessionData[], onClose: () => void }) => {
    // Use profiles from report if available (new AI feature), otherwise fallback to session data
    const profiles = report.participantProfiles;

    return (
       <div id="report-modal-container" className="fixed inset-0 z-50 bg-white" style={{ overflowY: 'auto' }}>
           {/* PRINT STYLE INJECTION */}
           <style>{`
               @media print {
                   @page { margin: 0; size: auto; }
                   html, body, #root, #root > div { height: auto !important; overflow: visible !important; position: static !important; width: auto !important; min-height: 0 !important; }
                   body * { visibility: hidden; }
                   #report-modal-container { visibility: visible !important; position: absolute !important; top: 0 !important; left: 0 !important; width: 100vw !important; height: auto !important; overflow: visible !important; margin: 0 !important; padding: 0 !important; background: white !important; z-index: 9999 !important; display: block !important; }
                   #report-modal-container * { visibility: visible !important; }
                   #report-controls { display: none !important; }
                   section { break-inside: avoid; page-break-inside: avoid; }
                   * { -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; }
               }
           `}</style>

           {/* Minimalist Top Bar */}
           <div id="report-controls" className="sticky top-0 bg-white/95 backdrop-blur border-b border-gray-200 px-8 py-4 flex justify-between items-center z-10">
               <div className="flex items-center gap-4">
                    <button onClick={onClose} className="p-2 hover:bg-gray-100 rounded-full transition-colors">
                       <svg className="w-6 h-6 text-black" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                           <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M6 18L18 6M6 6l12 12" />
                       </svg>
                    </button>
                    <span className="text-xs font-bold text-gray-400 uppercase tracking-widest">Confidential · Project Analysis</span>
               </div>
               
               <div className="flex items-center gap-3">
                   <button 
                       onClick={() => window.print()}
                       className="text-sm font-bold text-black border border-black px-4 py-2 rounded hover:bg-black hover:text-white transition-colors flex items-center gap-2"
                   >
                       <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" /></svg>
                       Export Report (PDF)
                   </button>
               </div>
           </div>

           <div id="report-printable-area" className="max-w-4xl mx-auto px-10 py-10 font-sans text-gray-900 bg-white min-h-screen">
               {/* Title Page Style Header */}
               <div className="mb-10 border-b-2 border-black pb-6">
                   <h1 className="text-3xl font-serif font-bold leading-tight mb-4 text-black">
                       {report.title}
                   </h1>
                   <div className="flex justify-between items-end">
                        <div className="text-xs text-gray-500 font-medium">
                           <p>Generated by InsightFlow AI</p>
                           <p>{new Date(report.generatedAt).toLocaleDateString()}</p>
                        </div>
                        <div className="text-right">
                            <div className="text-3xl font-bold text-blue-900">{sessions?.length || 0}</div>
                            <div className="text-[10px] text-gray-400 uppercase tracking-wider font-bold">Sessions Analyzed</div>
                        </div>
                   </div>
               </div>

               {/* Participant Overview Section (Personalized Card Style) */}
               <div className="mb-12 break-inside-avoid page-break-inside-avoid">
                   <div className="mb-4">
                        <h2 className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-2 border-b border-gray-100 pb-1">
                           PARTICIPANT PROFILES
                       </h2>
                       <p className="text-xs text-gray-600 leading-relaxed max-w-2xl">
                           Analyzed {sessions?.length || 0} representative target users via AI In-depth Interview.
                       </p>
                   </div>

                   {/* Boxed Grid for Participants matching screenshot style */}
                   <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                       {profiles && profiles.length > 0 ? (
                            profiles.map((p, idx) => (
                                <div key={idx} className="border border-gray-300 p-6 rounded-sm bg-white break-inside-avoid shadow-sm hover:shadow-md transition-shadow">
                                   <div className="flex items-baseline gap-2 mb-4">
                                       <h3 className="text-lg font-bold text-black tracking-tight">
                                           {p.pseudonym}, <span className="text-lg font-normal text-black">{p.roleAndAge}</span>
                                       </h3>
                                   </div>
                                   <div className="text-sm text-gray-600 leading-relaxed font-normal">
                                       {[p.occupation, ...p.tags].filter(Boolean).join(', ')}
                                   </div>
                               </div>
                            ))
                       ) : (
                           // Fallback for old reports
                           sessions?.map((s, idx) => {
                               const name = `Anonymous User ${String(idx + 1).padStart(2, '0')}`;
                               const role = s.context.objectType;
                               const desc = s.context.userPersona || 'No description';
                               
                               return (
                                   <div key={s.id} className="border border-gray-300 p-6 rounded-sm bg-white break-inside-avoid shadow-sm">
                                       <div className="flex justify-between items-start mb-4">
                                           <span className="font-bold text-lg text-black">{name}</span>
                                       </div>
                                       <div className="text-sm text-gray-600 leading-relaxed">
                                            {role}, {desc}
                                       </div>
                                   </div>
                               )
                           })
                       )}
                   </div>
               </div>

               {/* Chapters */}
               <div className="space-y-12">
                   {report.chapters?.map((chapter, idx) => (
                       <section key={idx} className="break-inside-avoid page-break-inside-avoid">
                           {/* Chapter Header - Compact */}
                           <div className="flex items-baseline gap-3 mb-4 border-b border-gray-200 pb-1">
                               <span className="text-4xl font-serif font-bold text-gray-200 select-none">
                                   {String(idx + 1).padStart(2, '0')}
                               </span>
                               <h2 className="text-xl font-bold text-black uppercase tracking-wide flex-1">
                                   {chapter.title}
                               </h2>
                           </div>

                           {/* Content Layout */}
                           <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
                               {/* Main Content */}
                               <div className="lg:col-span-8">
                                   {renderMarkdownContent(chapter.content)}
                               </div>

                               {/* Sidebar / Key Takeaways - Compact */}
                               <div className="lg:col-span-4">
                                    {chapter.keyTakeaways && chapter.keyTakeaways.length > 0 && (
                                        <div className="bg-gray-50 p-4 border-l-2 border-blue-900 rounded-r">
                                            <h3 className="text-[10px] font-bold text-blue-900 uppercase tracking-widest mb-2">
                                                Key Takeaways
                                            </h3>
                                            <ul className="space-y-2">
                                                {chapter.keyTakeaways.map((point, k) => (
                                                    <li key={k} className="text-xs font-medium text-gray-800 leading-snug flex gap-2">
                                                        <span className="text-blue-900/50">•</span>
                                                        <span>{point.replace(/\*\*/g, '').replace(/\*/g, '')}</span>
                                                    </li>
                                                ))}
                                            </ul>
                                        </div>
                                    )}
                               </div>
                           </div>
                       </section>
                   ))}
               </div>

               {/* Footer */}
               <div className="mt-20 pt-4 border-t border-gray-100 text-center text-[10px] text-gray-400 font-mono uppercase">
                   CONFIDENTIAL · INSIGHTFLOW AI ANALYSIS · DO NOT DISTRIBUTE
               </div>
           </div>
       </div>
    );
 };

export const GlobalDashboard: React.FC<GlobalDashboardProps> = ({ onBack }) => {
  const { t } = useLanguage();
  const [allSessions, setAllSessions] = useState<SessionData[]>([]);
  const [loading, setLoading] = useState(true);
  
  // Selection State
  const [selectedProjectTitle, setSelectedProjectTitle] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<'list' | 'report'>('list');
  const [viewingSessionId, setViewingSessionId] = useState<string | null>(null);
  
  // Analysis & Report State
  const [analyzingIds, setAnalyzingIds] = useState<Set<string>>(new Set());
  const [isGeneratingReport, setIsGeneratingReport] = useState(false);
  const [projectReport, setProjectReport] = useState<ProjectReport | null>(null);
  const [showReportModal, setShowReportModal] = useState(false);
  const [linkCopied, setLinkCopied] = useState(false);

  // 1. Load Data
  useEffect(() => {
    const loadData = async () => {
        try {
            const data = await getAllSessions();
            setAllSessions(data);
            if (data.length > 0 && !selectedProjectTitle) {
                // Default to most recent project
                setSelectedProjectTitle(data[0].plan.title);
            }
        } catch(e) {
            console.error(e);
        } finally {
            setLoading(false);
        }
    };
    loadData();
  }, []);

  // 2. Group Data by Project Title
  const groupedProjects = useMemo(() => {
    const groups: Record<string, SessionData[]> = {};
    allSessions.forEach(s => {
        const title = s.plan.title;
        if (!groups[title]) groups[title] = [];
        groups[title].push(s);
    });
    return groups;
  }, [allSessions]);

  const projectTitles = Object.keys(groupedProjects);
  const currentProjectSessions = selectedProjectTitle ? groupedProjects[selectedProjectTitle] || [] : [];
  
  // Sort sessions: Completed first, then by date
  const sortedSessions = useMemo(() => {
      return [...currentProjectSessions].sort((a, b) => {
          if (a.transcript && !b.transcript) return -1;
          if (!a.transcript && b.transcript) return 1;
          return b.timestamp - a.timestamp;
      });
  }, [currentProjectSessions]);

  // Derived Stats
  const totalParticipants = currentProjectSessions.length;
  const completedConversations = currentProjectSessions.filter(s => s.transcript).length;
  
  // Construct Share URL
  const projectShareUrl = useMemo(() => {
      if (!currentProjectSessions.length) return '';
      const baseId = currentProjectSessions[currentProjectSessions.length - 1].id;
      return `${window.location.origin}${window.location.pathname}?session=${baseId}`;
  }, [currentProjectSessions]);

  // --- Actions ---

  const handleCopyLink = () => {
      if (!projectShareUrl) return;
      navigator.clipboard.writeText(projectShareUrl);
      setLinkCopied(true);
      setTimeout(() => setLinkCopied(false), 2000);
  };

  const handleViewSession = (id: string) => {
      setViewingSessionId(id);
      setActiveTab('report');
      
      const session = currentProjectSessions.find(s => s.id === id);
      if (session && session.transcript && !session.analysis && !analyzingIds.has(id)) {
          handleAnalyzeSession(session);
      }
  };

  const handleAnalyzeSession = async (session: SessionData) => {
    if (!session.transcript) return;
    setAnalyzingIds(prev => new Set(prev).add(session.id));
    try {
        const result = await analyzeTranscripts(session.transcript);
        const updatedSession = { ...session, analysis: result };
        await saveSession(updatedSession);
        setAllSessions(prev => prev.map(s => s.id === session.id ? updatedSession : s));
    } catch (e) {
        console.error("Dashboard analysis failed", e);
    } finally {
        setAnalyzingIds(prev => {
            const next = new Set(prev);
            next.delete(session.id);
            return next;
        });
    }
  };

  const handleGenerateProjectReport = async () => {
    if (!selectedProjectTitle) return;

    const cached = await getProjectReport(selectedProjectTitle);
    if (cached) {
        setProjectReport(cached);
        setShowReportModal(true);
        return;
    }

    setIsGeneratingReport(true);
    try {
        const report = await generateProjectReport(selectedProjectTitle, currentProjectSessions);
        await saveProjectReport(selectedProjectTitle, report);
        setProjectReport(report);
        setShowReportModal(true);
    } catch (e: any) {
        alert(`Report Generation Failed: ${e.message}`);
    } finally {
        setIsGeneratingReport(false);
    }
  };

  const currentViewingSession = viewingSessionId 
    ? currentProjectSessions.find(s => s.id === viewingSessionId) 
    : (sortedSessions.length > 0 ? sortedSessions[0] : null);

  const CustomTreemapContent = (props: any) => {
    const { x, y, width, height, index, name } = props;
    
    // Safety check
    if (!width || !height) return null;

    // 1. Smart Font Scaling
    // Calculate fit based on width and character count
    const charCount = name.length;
    const availableWidth = width - 8; 
    
    // Calculate theoretical font size to fill width
    let calculatedFontSize = availableWidth / charCount;
    
    // Clamp max size based on height (to avoid vertical overflow)
    calculatedFontSize = Math.min(calculatedFontSize, height * 0.5);
    
    // Clamp absolute limits (11px to 20px) to prevent tiny or massive text
    const fontSize = Math.min(Math.max(calculatedFontSize, 11), 20);

    // 2. Visibility Threshold
    // If box is too small for even minimal text, hide it
    const isVisible = width > 32 && height > 24 && (fontSize * charCount <= width + 8);

    return (
      <g>
        <rect
          x={x}
          y={y}
          width={width}
          height={height}
          style={{
            fill: HEATMAP_COLORS[index % HEATMAP_COLORS.length],
            stroke: '#fff',
            strokeWidth: 2,
          }}
          rx={8} 
          ry={8}
        />
        {isVisible && (
          <text
            x={x + width / 2}
            y={y + height / 2}
            textAnchor="middle"
            dominantBaseline="middle"
            fill="#fff"
            fontSize={fontSize}
            fontWeight={600}
            style={{ pointerEvents: 'none' }}
          >
            {name}
          </text>
        )}
      </g>
    );
  };

  return (
    <div className="h-screen bg-ios-bg text-black font-sans flex flex-col overflow-hidden">
      
      {/* Top Navbar */}
      <nav className="h-16 flex items-center justify-between px-6 bg-white border-b border-gray-200 shrink-0 z-20 shadow-sm">
        <div className="flex items-center gap-4">
            <button onClick={onBack} className="p-2 hover:bg-gray-100 rounded-lg transition-colors text-gray-500 hover:text-black">
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M15 19l-7-7 7-7" />
                </svg>
            </button>
            <h1 className="text-lg font-bold text-black tracking-tight flex items-center gap-2">
                <div className="w-2 h-2 rounded-full bg-ios-green shadow-sm"></div>
                {t('global.title')}
            </h1>
        </div>
        <div className="flex gap-6 text-xs font-bold text-gray-400 uppercase tracking-wider">
            <div>{t('global.projects')}: <span className="text-black ml-1">{projectTitles.length}</span></div>
            <div>{t('global.responses')}: <span className="text-black ml-1">{allSessions.filter(s => s.transcript).length}</span></div>
        </div>
      </nav>

      {/* Main Content Area */}
      <div className="flex-1 flex overflow-hidden">
          
          {/* Sidebar - Project List */}
          <div className="w-64 bg-white border-r border-gray-200 flex flex-col shrink-0">
             <div className="p-4">
                 <h2 className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-4">{t('global.list_title')}</h2>
                 <div className="space-y-1">
                    {projectTitles.map((title) => (
                        <button
                            key={title}
                            onClick={() => { setSelectedProjectTitle(title); setActiveTab('list'); setViewingSessionId(null); }}
                            className={`w-full text-left p-3 rounded-lg transition-all duration-200 text-sm font-medium truncate ${
                                selectedProjectTitle === title 
                                ? 'bg-ios-blue/10 text-ios-blue ring-1 ring-ios-blue/20 shadow-sm' 
                                : 'text-gray-600 hover:bg-gray-50 hover:text-black'
                            }`}
                        >
                            {title}
                        </button>
                    ))}
                 </div>
             </div>
          </div>

          {/* Center Stage */}
          <div className="flex-1 overflow-y-auto custom-scrollbar bg-ios-bg p-8">
             <div className="max-w-6xl mx-auto space-y-8">
                 
                 {/* Top Stats Cards */}
                 <div className="grid grid-cols-1 lg:grid-cols-12 gap-4">
                     {/* Title Card */}
                     <div className="lg:col-span-5 bg-white rounded-2xl p-6 border border-gray-200 shadow-sm relative overflow-hidden group">
                         <div className="absolute top-0 right-0 w-32 h-32 bg-blue-50 rounded-full blur-2xl -mr-8 -mt-8 pointer-events-none"></div>
                         <div className="flex items-center justify-between mb-2 relative z-10">
                             <div className="flex items-center gap-3">
                                <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-green-50 text-ios-green border border-green-100">{t('global.status.active')}</span>
                                <span className="text-xs text-gray-400 uppercase tracking-wider">{t('global.overview')}</span>
                             </div>
                             
                             {/* REPORT BUTTON */}
                             {selectedProjectTitle && (
                                <button 
                                    onClick={handleGenerateProjectReport}
                                    disabled={isGeneratingReport || totalParticipants === 0}
                                    className={`text-xs font-bold px-3 py-1.5 rounded-lg border transition-all flex items-center gap-1.5 ${
                                        isGeneratingReport 
                                        ? 'bg-gray-100 text-gray-400 border-transparent cursor-not-allowed'
                                        : 'bg-black text-white border-black hover:bg-gray-800 shadow-md active:scale-95'
                                    }`}
                                >
                                    {isGeneratingReport ? (
                                        <>
                                            <div className="w-3 h-3 border-2 border-current border-t-transparent rounded-full animate-spin"></div>
                                            {t('global.generating')}
                                        </>
                                    ) : (
                                        <>
                                            <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
                                            {t('global.generate_report')}
                                        </>
                                    )}
                                </button>
                             )}
                         </div>
                         <h2 className="text-xl font-bold text-black leading-snug mb-1 truncate relative z-10">
                             {selectedProjectTitle || "No Selection"}
                         </h2>
                         <p className="text-sm text-gray-500 truncate relative z-10">
                             {isGeneratingReport 
                                ? "InsightFlow AI is analyzing all sessions..." 
                                : "Analyze user interviews and extract key insights."
                             }
                         </p>
                     </div>

                     {/* Project Link Card */}
                     <div className="lg:col-span-3 bg-white rounded-2xl p-5 border border-gray-200 shadow-sm flex flex-col justify-center">
                         <div className="flex items-center gap-2 mb-2">
                             <div className="w-4 h-4 rounded bg-purple-100 text-purple-600 flex items-center justify-center">
                                <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1" />
                                </svg>
                             </div>
                             <span className="text-xs text-gray-400 font-bold uppercase">{t('global.link')}</span>
                         </div>
                         
                         <div className="flex items-center gap-2 bg-gray-50 rounded-lg p-1.5 border border-gray-100">
                            <div className="flex-1 text-[10px] text-gray-500 truncate select-all font-mono">
                                {projectShareUrl || 'N/A'}
                            </div>
                            <button 
                                onClick={handleCopyLink}
                                disabled={!projectShareUrl}
                                className={`p-1.5 rounded-md transition-all ${
                                    linkCopied 
                                    ? 'bg-green-500 text-white' 
                                    : 'bg-white text-black border border-gray-200 hover:bg-gray-100'
                                }`}
                                title="Copy"
                            >
                                {linkCopied ? (
                                    <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M5 13l4 4L19 7" /></svg>
                                ) : (
                                    <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3" /></svg>
                                )}
                            </button>
                         </div>
                     </div>

                     {/* Stat 1 */}
                     <div className="lg:col-span-2 bg-white rounded-2xl p-5 border border-gray-200 shadow-sm flex flex-col justify-center">
                         <div className="flex items-center gap-2 mb-1">
                             <svg className="w-4 h-4 text-ios-blue" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" /></svg>
                             <span className="text-xs text-gray-400 font-bold uppercase">{t('global.participants')}</span>
                         </div>
                         <span className="text-2xl font-bold text-black">{totalParticipants}</span>
                     </div>

                     {/* Stat 2 */}
                     <div className="lg:col-span-2 bg-white rounded-2xl p-5 border border-gray-200 shadow-sm flex flex-col justify-center">
                         <div className="flex items-center gap-2 mb-1">
                             <svg className="w-4 h-4 text-ios-green" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
                             <span className="text-xs text-gray-400 font-bold uppercase">{t('global.completed')}</span>
                         </div>
                         <span className="text-2xl font-bold text-black">{completedConversations}</span>
                     </div>
                 </div>

                 {/* Tabs */}
                 <div className="flex items-center gap-6 border-b border-gray-200 pb-1">
                     <button 
                        onClick={() => setActiveTab('list')}
                        className={`pb-3 text-sm font-bold transition-all relative ${activeTab === 'list' ? 'text-black' : 'text-gray-400 hover:text-black'}`}
                     >
                         {t('global.tab.list')}
                         {activeTab === 'list' && <div className="absolute bottom-[-1px] left-0 w-full h-0.5 bg-ios-blue rounded-full"></div>}
                     </button>
                 </div>

                 {/* Tab Content */}
                 {activeTab === 'list' && (
                     <div className="bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden">
                         <div className="p-6 border-b border-gray-100 flex justify-between items-center">
                             <h3 className="font-bold text-black">{t('global.tab.list')} ({currentProjectSessions.length})</h3>
                             <button className="text-xs flex items-center gap-1 text-gray-500 hover:text-black transition-colors">
                                 <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" /></svg>
                                 Refresh
                             </button>
                         </div>
                         
                         {/* Table */}
                         <div className="overflow-x-auto">
                            <table className="w-full text-left">
                                <thead className="bg-gray-50 text-xs uppercase text-gray-400 font-bold">
                                    <tr>
                                        <th className="px-6 py-4">{t('global.list.header.participant')}</th>
                                        <th className="px-6 py-4">{t('global.list.header.status')}</th>
                                        <th className="px-6 py-4">{t('global.list.header.date')}</th>
                                        <th className="px-6 py-4">{t('global.list.header.type')}</th>
                                        <th className="px-6 py-4">{t('global.list.header.msgs')}</th>
                                        <th className="px-6 py-4 text-right">{t('global.list.header.action')}</th>
                                    </tr>
                                </thead>
                                <tbody className="divide-y divide-gray-100">
                                    {sortedSessions.map((s, idx) => (
                                        <tr key={s.id} className="group hover:bg-gray-50 transition-colors">
                                            <td className="px-6 py-4">
                                                <div className="flex items-center gap-3">
                                                    <div className="w-8 h-8 rounded-full bg-gray-100 flex items-center justify-center text-xs font-bold text-gray-500 border border-gray-200">
                                                        #{currentProjectSessions.length - idx}
                                                    </div>
                                                    <span className="text-sm font-medium text-black">{s.context.objectType}</span>
                                                </div>
                                            </td>
                                            <td className="px-6 py-4">
                                                {s.transcript ? (
                                                    <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[10px] font-bold bg-green-50 text-ios-green border border-green-100">
                                                        <div className="w-1.5 h-1.5 rounded-full bg-ios-green"></div>
                                                        {t('global.status.done')}
                                                    </span>
                                                ) : (
                                                    <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[10px] font-bold bg-gray-100 text-gray-400 border border-gray-200">
                                                        <div className="w-1.5 h-1.5 rounded-full bg-gray-400"></div>
                                                        {t('global.status.active')}
                                                    </span>
                                                )}
                                            </td>
                                            <td className="px-6 py-4 text-sm text-gray-500">
                                                {new Date(s.timestamp).toLocaleDateString()} <span className="text-[10px] opacity-60 ml-1">{new Date(s.timestamp).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'})}</span>
                                            </td>
                                            <td className="px-6 py-4 text-sm text-black">
                                                {s.context.method === 'voice' ? t('global.type.voice') : t('global.type.quest')}
                                            </td>
                                            <td className="px-6 py-4 text-sm text-gray-500 flex items-center gap-2">
                                                <svg className="w-4 h-4 opacity-50" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 10h.01M12 10h.01M16 10h.01M9 16H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-5l-5 5v-5z" /></svg>
                                                {s.transcript ? (s.transcript as any).length || 20 : 0}
                                            </td>
                                            <td className="px-6 py-4 text-right">
                                                <button 
                                                    onClick={() => handleViewSession(s.id)}
                                                    className="text-ios-blue hover:text-blue-700 text-xs font-bold transition-colors flex items-center justify-end gap-1 w-full"
                                                >
                                                    <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" /></svg>
                                                    {t('global.action.view')}
                                                </button>
                                            </td>
                                        </tr>
                                    ))}
                                    {sortedSessions.length === 0 && (
                                        <tr>
                                            <td colSpan={6} className="px-6 py-12 text-center text-gray-400">
                                                {t('global.empty')}
                                            </td>
                                        </tr>
                                    )}
                                </tbody>
                            </table>
                         </div>
                     </div>
                 )}

                 {activeTab === 'report' && currentViewingSession && (
                     <div className="space-y-6 animate-in fade-in slide-in-from-bottom-2 duration-300">
                         {/* Session Header inside Report */}
                         <div className="flex justify-between items-center bg-white p-6 rounded-2xl border border-gray-200 shadow-sm">
                             <div>
                                 <h3 className="font-bold text-black text-lg">{t('global.report.title')}</h3>
                                 <p className="text-sm text-gray-500">Session ID: {currentViewingSession.id}</p>
                             </div>
                             {analyzingIds.has(currentViewingSession.id) && (
                                 <div className="flex items-center gap-2 text-ios-blue text-sm font-bold animate-pulse">
                                     <div className="w-4 h-4 border-2 border-current border-t-transparent rounded-full animate-spin"></div>
                                     {t('global.analyzing')}
                                 </div>
                             )}
                         </div>

                         {currentViewingSession.analysis ? (
                             <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                                 {/* Summary Report Card */}
                                 <div className="md:col-span-3 bg-gradient-to-br from-white to-gray-50 rounded-2xl p-8 border border-gray-200 shadow-sm relative overflow-hidden">
                                     <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-ios-blue to-purple-400"></div>
                                     <h4 className="text-gray-900 font-bold mb-6 text-sm uppercase tracking-widest flex items-center gap-3 border-b border-gray-100 pb-4">
                                         <div className="w-8 h-8 rounded-lg bg-blue-50 text-ios-blue flex items-center justify-center">
                                            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
                                         </div>
                                         Deep Insight Report
                                     </h4>
                                     <div className="prose prose-sm max-w-none">
                                         {renderMarkdownContent(currentViewingSession.analysis.summary)}
                                     </div>
                                 </div>

                                 {/* Charts Row - OPTIMIZED UI */}
                                 <div className="bg-white rounded-2xl p-6 border border-gray-100 shadow-sm hover:shadow-md transition-shadow">
                                     <h4 className="text-gray-800 font-bold mb-6 text-sm flex items-center gap-2">
                                         <span className="w-1.5 h-1.5 rounded-full bg-ios-blue"></span> {t('global.report.topics')}
                                     </h4>
                                     <div className="h-48">
                                         <ResponsiveContainer width="100%" height="100%">
                                             <BarChart data={currentViewingSession.analysis.themes}>
                                                 <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" vertical={false} />
                                                 <XAxis dataKey="topic" hide />
                                                 <Tooltip 
                                                    contentStyle={{ backgroundColor: '#fff', border: '1px solid #e5e5e5', borderRadius: '8px', color: '#000', boxShadow: '0 4px 12px rgba(0,0,0,0.05)' }}
                                                    itemStyle={{ color: '#000' }}
                                                    cursor={{ fill: '#f9f9f9' }}
                                                 />
                                                 <defs>
                                                     <linearGradient id="barGradient" x1="0" y1="0" x2="0" y2="1">
                                                         <stop offset="0%" stopColor="#007AFF" stopOpacity={0.9}/>
                                                         <stop offset="100%" stopColor="#0055B3" stopOpacity={0.9}/>
                                                     </linearGradient>
                                                 </defs>
                                                 <Bar dataKey="count" fill="url(#barGradient)" radius={[4, 4, 4, 4]} />
                                             </BarChart>
                                         </ResponsiveContainer>
                                     </div>
                                 </div>

                                 <div className="bg-white rounded-2xl p-6 border border-gray-100 shadow-sm hover:shadow-md transition-shadow">
                                     <h4 className="text-gray-800 font-bold mb-6 text-sm flex items-center gap-2">
                                         <span className="w-1.5 h-1.5 rounded-full bg-orange-500"></span> {t('global.report.sentiment')}
                                     </h4>
                                     <div className="h-48 relative">
                                         <ResponsiveContainer width="100%" height="100%">
                                             <PieChart>
                                                 <Pie
                                                     data={currentViewingSession.analysis.sentiment}
                                                     cx="50%"
                                                     cy="50%"
                                                     innerRadius={45}
                                                     outerRadius={65}
                                                     paddingAngle={4}
                                                     dataKey="value"
                                                     stroke="none"
                                                 >
                                                     {currentViewingSession.analysis.sentiment.map((entry, index) => {
                                                         // Map colors semantically if possible
                                                         let fillColor = BASE_COLORS[index % BASE_COLORS.length];
                                                         if (entry.name.includes('积') || entry.name.includes('Positive')) fillColor = SENTIMENT_COLORS.positive;
                                                         else if (entry.name.includes('消') || entry.name.includes('Negative')) fillColor = SENTIMENT_COLORS.negative;
                                                         else if (entry.name.includes('中') || entry.name.includes('Neutral')) fillColor = SENTIMENT_COLORS.neutral;
                                                         
                                                         return <Cell key={`cell-${index}`} fill={fillColor} />;
                                                     })}
                                                 </Pie>
                                                 <Tooltip 
                                                     contentStyle={{ backgroundColor: '#fff', borderRadius: '8px', border: '1px solid #e5e5e5', color: '#000', boxShadow: '0 4px 12px rgba(0,0,0,0.05)' }} 
                                                     itemStyle={{ color: '#000' }}
                                                 />
                                             </PieChart>
                                         </ResponsiveContainer>
                                         <div className="absolute inset-0 pointer-events-none flex items-center justify-center">
                                             <div className="text-center">
                                                 <span className="text-[10px] font-bold text-gray-400 block tracking-wider uppercase">SENTIMENT</span>
                                             </div>
                                         </div>
                                     </div>
                                 </div>

                                 <div className="bg-white rounded-2xl p-6 border border-gray-100 shadow-sm hover:shadow-md transition-shadow">
                                     <h4 className="text-gray-800 font-bold mb-6 text-sm flex items-center gap-2">
                                         <span className="w-1.5 h-1.5 rounded-full bg-purple-500"></span> {t('global.report.keywords')}
                                     </h4>
                                     <div className="h-48 overflow-hidden rounded-xl bg-gray-50 border border-gray-100">
                                         {currentViewingSession.analysis.keywords && currentViewingSession.analysis.keywords.length > 0 ? (
                                             <ResponsiveContainer width="100%" height="100%">
                                                 <Treemap
                                                     data={currentViewingSession.analysis.keywords.map(k => ({ name: k.word, size: k.count }))}
                                                     dataKey="size"
                                                     aspectRatio={4 / 3}
                                                     stroke="#fff"
                                                     content={<CustomTreemapContent />}
                                                 >
                                                     <Tooltip contentStyle={{ backgroundColor: '#fff', borderRadius: '8px', border: '1px solid #e5e5e5', color: '#000', boxShadow: '0 4px 12px rgba(0,0,0,0.05)' }} />
                                                 </Treemap>
                                             </ResponsiveContainer>
                                         ) : (
                                             <div className="h-full flex items-center justify-center text-gray-400 text-xs">
                                                 N/A
                                             </div>
                                         )}
                                     </div>
                                 </div>
                             </div>
                         ) : (
                             <div className="p-12 text-center text-gray-400 bg-white rounded-2xl border border-gray-200 border-dashed">
                                 {sessionIsAnalyzable(currentViewingSession) ? (
                                     t('global.waiting')
                                 ) : (
                                     t('global.no_result')
                                 )}
                             </div>
                         )}
                     </div>
                 )}
                 
                 {activeTab === 'report' && !currentViewingSession && (
                     <div className="flex flex-col items-center justify-center py-20 text-gray-400">
                         <p>{t('global.select_hint')}</p>
                     </div>
                 )}

             </div>
          </div>
      </div>

      {/* Report Modal */}
      {showReportModal && projectReport && (
          <McKinseyReportView 
              report={projectReport} 
              sessions={currentProjectSessions}
              onClose={() => setShowReportModal(false)} 
          />
      )}
    </div>
  );
};

// Helper
function sessionIsAnalyzable(s: SessionData | null) {
    return s && s.transcript;
}